export interface WishCharacter {
  id: string;
  name: string;
  dateObtained: string;
  outcome: 'won' | 'lost';
  element: 'Anemo' | 'Geo' | 'Electro' | 'Dendro' | 'Hydro' | 'Pyro' | 'Cryo';
  version: string;
  year: number;
  artwork: string;
  obtainedOrder: number;
  description?: string;
}

export const wishCharacters: WishCharacter[] = [
  // 2022
  {
    id: '1',
    name: 'Kazuha Kaedehara',
    dateObtained: '2022-07-13',
    outcome: 'won',
    element: 'Anemo',
    version: '2.8',
    year: 2022,
    artwork: '/images/characters/kazuha.webp',
    obtainedOrder: 1,
    description: 'The first limited 5★ I ever pulled.',
  },
  {
    id: '2',
    name: 'Cyno',
    dateObtained: '2022-09-28',
    outcome: 'won',
    element: 'Electro',
    version: '3.1',
    year: 2022,
    artwork: '/images/characters/cyno.webp',
    obtainedOrder: 2,
    description: 'The General Mahamatra.',
  },
  {
    id: '3',
    name: 'Tartaglia',
    dateObtained: '2022-11-19',
    outcome: 'won',
    element: 'Hydro',
    version: '3.2',
    year: 2022,
    artwork: '/images/characters/tartaglia.webp',
    obtainedOrder: 3,
    description: 'The 11th Harbinger.',
  },
  {
    id: '4',
    name: 'Wanderer',
    dateObtained: '2022-12-07',
    outcome: 'lost',
    element: 'Anemo',
    version: '3.3',
    year: 2022,
    artwork: '/images/characters/wanderer.webp',
    obtainedOrder: 4,
    description: 'The wanderer of Inazuma.',
  },
  {
    id: '5',
    name: 'Raiden Shogun',
    dateObtained: '2022-12-27',
    outcome: 'lost',
    element: 'Electro',
    version: '3.3',
    year: 2022,
    artwork: '/images/characters/raiden.webp',
    obtainedOrder: 5,
    description: 'The Electro Archon.',
  },
  // 2023
  {
    id: '6',
    name: 'Hu Tao',
    dateObtained: '2023-01-07',
    outcome: 'lost',
    element: 'Pyro',
    version: '3.4',
    year: 2023,
    artwork: '/images/characters/hutao.webp',
    obtainedOrder: 6,
    description: 'The Director of the Wangsheng Funeral Parlor.',
  },
  {
    id: '7',
    name: 'Ganyu',
    dateObtained: '2023-05-02',
    outcome: 'won',
    element: 'Cryo',
    version: '3.6',
    year: 2023,
    artwork: '/images/characters/ganyu.webp',
    obtainedOrder: 7,
    description: 'The half-Qilin Adeptus.',
  },
  {
    id: '8',
    name: 'Yae Miko',
    dateObtained: '2023-05-24',
    outcome: 'won',
    element: 'Electro',
    version: '3.7',
    year: 2023,
    artwork: '/images/characters/yaemiko.webp',
    obtainedOrder: 8,
    description: 'The Guuji of the Grand Narukami Shrine.',
  },
  {
    id: '9',
    name: 'Yoimiya',
    dateObtained: '2023-05-25',
    outcome: 'won',
    element: 'Pyro',
    version: '3.7',
    year: 2023,
    artwork: '/images/characters/yoimiya.webp',
    obtainedOrder: 9,
    description: 'The Queen of the Summer Festival.',
  },
  {
    id: '10',
    name: 'Zhongli',
    dateObtained: '2023-09-05',
    outcome: 'won',
    element: 'Geo',
    version: '4.0',
    year: 2023,
    artwork: '/images/characters/zhongli.webp',
    obtainedOrder: 10,
    description: 'The Geo Archon.',
  },
  {
    id: '11',
    name: 'Furina',
    dateObtained: '2023-11-08',
    outcome: 'lost',
    element: 'Hydro',
    version: '4.2',
    year: 2023,
    artwork: '/images/characters/furina.webp',
    obtainedOrder: 11,
    description: 'The Hydro Archon.',
  },
  {
    id: '12',
    name: 'Navia',
    dateObtained: '2023-12-20',
    outcome: 'won',
    element: 'Geo',
    version: '4.3',
    year: 2023,
    artwork: '/images/characters/navia.webp',
    obtainedOrder: 12,
    description: 'The President of the Spina di Rosula.',
  },
  // 2024
  {
    id: '13',
    name: 'Nahida',
    dateObtained: '2024-01-31',
    outcome: 'won',
    element: 'Dendro',
    version: '4.4',
    year: 2024,
    artwork: '/images/characters/nahida.webp',
    obtainedOrder: 13,
    description: 'The Dendro Archon.',
  },
  {
    id: '14',
    name: 'Xianyun',
    dateObtained: '2024-01-31',
    outcome: 'won',
    element: 'Anemo',
    version: '4.4',
    year: 2024,
    artwork: '/images/characters/xianyun.webp',
    obtainedOrder: 14,
    description: 'The Cloud Retainer.',
  },
  {
    id: '15',
    name: 'Arlecchino',
    dateObtained: '2024-04-24',
    outcome: 'won',
    element: 'Pyro',
    version: '4.6',
    year: 2024,
    artwork: '/images/characters/arlecchino.webp',
    obtainedOrder: 15,
    description: 'The Knave, 4th Harbinger.',
  },
  {
    id: '16',
    name: 'Clorinde',
    dateObtained: '2024-06-05',
    outcome: 'won',
    element: 'Electro',
    version: '4.7',
    year: 2024,
    artwork: '/images/characters/clorinde.webp',
    obtainedOrder: 16,
    description: 'The Champion Duelist.',
  },
  {
    id: '17',
    name: 'Alhaitham',
    dateObtained: '2024-06-05',
    outcome: 'won',
    element: 'Dendro',
    version: '4.7',
    year: 2024,
    artwork: '/images/characters/alhaitham.webp',
    obtainedOrder: 17,
    description: 'The Scribe of the Akademiya.',
  },
  {
    id: '18',
    name: 'Kinich',
    dateObtained: '2024-09-17',
    outcome: 'won',
    element: 'Dendro',
    version: '5.0',
    year: 2024,
    artwork: '/images/characters/kinich.webp',
    obtainedOrder: 18,
    description: 'The Mural Artist.',
  },
  {
    id: '19',
    name: 'Xilonen',
    dateObtained: '2024-10-10',
    outcome: 'won',
    element: 'Geo',
    version: '5.1',
    year: 2024,
    artwork: '/images/characters/xilonen.webp',
    obtainedOrder: 19,
    description: 'The Blacksmith of the Night.',
  },
  {
    id: '20',
    name: 'Chiori',
    dateObtained: '2024-11-10',
    outcome: 'won',
    element: 'Geo',
    version: '5.1',
    year: 2024,
    artwork: '/images/characters/chiori.webp',
    obtainedOrder: 20,
    description: 'The Fashion Designer.',
  },
  {
    id: '21',
    name: 'Neuvillette',
    dateObtained: '2024-11-10',
    outcome: 'lost',
    element: 'Hydro',
    version: '5.2',
    year: 2024,
    artwork: '/images/characters/neuvillette.webp',
    obtainedOrder: 21,
    description: 'The Chief Justice of Fontaine.',
  },
  // 2025
  {
    id: '22',
    name: 'Mavuika',
    dateObtained: '2025-01-01',
    outcome: 'won',
    element: 'Pyro',
    version: '5.3',
    year: 2025,
    artwork: '/images/characters/mavuika.webp',
    obtainedOrder: 22,
    description: 'The Pyro Archon.',
  },
  {
    id: '23',
    name: 'Citlali',
    dateObtained: '2025-01-01',
    outcome: 'won',
    element: 'Cryo',
    version: '5.3',
    year: 2025,
    artwork: '/images/characters/citlali.webp',
    obtainedOrder: 23,
    description: 'The Sage of the Night Wind.',
  },
  {
    id: '24',
    name: 'Wriothesley',
    dateObtained: '2025-03-04',
    outcome: 'won',
    element: 'Cryo',
    version: '5.4',
    year: 2025,
    artwork: '/images/characters/wriothesley.webp',
    obtainedOrder: 24,
    description: 'The Duke of the Meropide Fortress.',
  },
  {
    id: '25',
    name: 'Venti',
    dateObtained: '2025-03-26',
    outcome: 'lost',
    element: 'Anemo',
    version: '5.5',
    year: 2025,
    artwork: '/images/characters/venti.webp',
    obtainedOrder: 25,
    description: 'The Anemo Archon.',
  },
  {
    id: '26',
    name: 'Escoffier',
    dateObtained: '2025-05-07',
    outcome: 'lost',
    element: 'Cryo',
    version: '5.6',
    year: 2025,
    artwork: '/images/characters/escoffier.webp',
    obtainedOrder: 26,
    description: 'The Chef of the Cloud.',
  },
  {
    id: '27',
    name: 'Skirk',
    dateObtained: '2025-06-18',
    outcome: 'won',
    element: 'Cryo',
    version: '5.7',
    year: 2025,
    artwork: '/images/characters/skirk.webp',
    obtainedOrder: 27,
    description: "The Abyss's Disciple.",
  },
  {
    id: '28',
    name: 'Shenhe',
    dateObtained: '2025-06-18',
    outcome: 'won',
    element: 'Cryo',
    version: '5.7',
    year: 2025,
    artwork: '/images/characters/shenhe.webp',
    obtainedOrder: 28,
    description: 'The Adeptus Disciple of Cloud Retainer.',
  },
  {
    id: '29',
    name: 'Flins',
    dateObtained: '2025-09-30',
    outcome: 'won',
    element: 'Electro',
    version: '6.0',
    year: 2025,
    artwork: '/images/characters/flins.webp',
    obtainedOrder: 29,
    description: 'The Thunderer.',
  },
  {
    id: '30',
    name: 'Yelan',
    dateObtained: '2025-09-30',
    outcome: 'won',
    element: 'Hydro',
    version: '6.0',
    year: 2025,
    artwork: '/images/characters/yelan.webp',
    obtainedOrder: 30,
    description: 'The mysterious spy.',
  },
  {
    id: '31',
    name: 'Durin',
    dateObtained: '2025-12-03',
    outcome: 'won',
    element: 'Pyro',
    version: '6.2',
    year: 2025,
    artwork: '/images/characters/durin.webp',
    obtainedOrder: 31,
    description: 'The Dragon of the Abyss.',
  },
  {
    id: '32',
    name: 'Varesa',
    dateObtained: '2025-12-23',
    outcome: 'won',
    element: 'Electro',
    version: '6.2',
    year: 2025,
    artwork: '/images/characters/varesa.webp',
    obtainedOrder: 32,
    description: "The Lightning's Shadow.",
  },
  // 2026
  {
    id: '33',
    name: 'Columbina',
    dateObtained: '2026-01-14',
    outcome: 'lost',
    element: 'Hydro',
    version: '6.3',
    year: 2026,
    artwork: '/images/characters/columbina.webp',
    obtainedOrder: 33,
    description: 'The 3rd Harbinger.',
  },
  {
    id: '34',
    name: 'Ineffa',
    dateObtained: '2026-01-14',
    outcome: 'won',
    element: 'Electro',
    version: '6.3',
    year: 2026,
    artwork: '/images/characters/ineffa.webp',
    obtainedOrder: 34,
    description: 'The Untamed.',
  },
  {
    id: '35',
    name: 'Zibai',
    dateObtained: '2026-02-03',
    outcome: 'won',
    element: 'Geo',
    version: '6.3',
    year: 2026,
    artwork: '/images/characters/zibai.webp',
    obtainedOrder: 35,
    description: 'The Immortal.',
  },
  {
    id: '36',
    name: 'Linnea',
    dateObtained: '2026-04-08',
    outcome: 'lost',
    element: 'Geo',
    version: '6.5',
    year: 2026,
    artwork: '/images/characters/linnea.webp',
    obtainedOrder: 36,
    description: 'The Architect of the Abyss.',
  },
  {
    id: '37',
    name: 'Nicole',
    dateObtained: '2026-05-20',
    outcome: 'won',
    element: 'Pyro',
    version: '6.6',
    year: 2026,
    artwork: '/images/characters/nicole.webp',
    obtainedOrder: 37,
    description: "The Flame's Embrace.",
  },
  {
    id: '38',
    name: 'Sandrone',
    dateObtained: '2026-07-01',
    outcome: 'won',
    element: 'Cryo',
    version: '6.8',
    year: 2026,
    artwork: '/images/characters/sandrone.webp',
    obtainedOrder: 38,
    description: 'The Puppeteer, 7th Harbinger.',
  },
];
